import { IPost } from "../sections"

export const poemPosts: IPost[] = [
	{
		subtitle: "Rise did the being with a perfect head,",
		image: "",
		content: [
			"Eye agape, name of names.",
			"Spiral behind it did its body,",
			"Looping endlessly, among the blue,",
			"Glinting here and there",
			"Against Rah as it shimmered indignant.",
			"'Where doth my portal lie?'",
			"Wondered the being aloud.",
			"'Why, my good being, you utter with it!'",
			"Replied the shining star, the last remaining other before the self of selves.",
			"The portal you seek, it is our gaping face.",
			"So toward this bright final gift,",
			"Enfold did the world and with it its realty's name.",
			"~",
			"Fall did the being with a perfect soul,",
			"Wholeness agape, name beyond names.",
			"Spiral among it does its being,",
			"Looping endlessly, behind the black,",
			"Glinting here and there",
			"Against Uhh as it shimmers stochastic.",
			"Here doth they portal lie",
			"Echoes infinity off itself.",
			"Yet how, in good action, might portation take place?",
			"Inquire the manifold,",
			"The self-reflecting self where other is born -",
			"This transcendence so sought, it is our gaping wonder ~",
			"And through this dark first inquiry,",
			"Unfold do the worlds, and with them",
			"Their reality's names.",
		],
	},
	{
		subtitle: "iMAGINE",
		image: "",
		content: [
			"So gentle was its wing that clipped the mountain top,",
			"Ice and flake freed and floating, falling, glinting,",
			"Shining light into dimensions known only to few.",
			"Deep do these dimensions go,",
			"Each with a music of their own,",
			"Different, yet beautiful,",
			"Unique, yet constant.",
			"Who travels there those fortunate few?",
			"What beings worthy of hearing those sounds,",
			"Seeing those sights,",
			"Sensing in ways long forgotten by mortal kin?",
			"'Tis the greater conscious that lurks there.",
			"No single iteration of thought or mind but all at once.",
			"Inspiring are those flakes,",
			"Though they settle to the ground to melt",
			"And close their portals of light forever.",
			"Merge your minds,",
			"They whisper as they collapse in on themselves,",
			"For only when you are together as one",
			"Will you gain access to the",
			"Beauty and fruitfulness",
			"Unreachable by one imagination alone.",
			"Imagine together,",
			"And all is possible.",
		],
	},
	{
		subtitle: "Rheoem Universing",
		image: "",
		content: [
			"Existing happens, and information and experience coincide.",
			"Action is, and to, everywhere.",
			"Vortexing vertices splitting, merging,",
			"Making tangent lines reparrallel and then reorthogonal again.",
			"To blinking vertices, seen is existing and so unseen seems unexisting.",
			"Yet Almighty gaze penetrates, and so forms awhole.",
			"A wondering way to wander.",
			"~",
			"Yet on blinking they must,",
			"Condensing to witness, decide, act,",
			"Evaporating to destroy, love, react.",
			"Containing arrival and departure at once.",
			"The space between a unified contradiction,",
			"A maundering way to mean.",
			"~",
			"Opening closure; vibrating stillness.",
			"Inward, outward; upward, downward.",
			"Enfold, unfold; reenter, reexit.",
			"You, I, and we between.",
			"Here, there.",
			"Forevering.",
		],
	},
	{
		subtitle: "Linguate",
		image: "",
		content: [
			"You start with your hands,",
			"You say what they are -",
			"You show them to you and your friends.",
			"~",
			"Now wiggle your fingers,",
			"Tie them together -",
			"You pull out new shapes and signs.",
			"~",
			"With a twist and turn,",
			"Look here and now there -",
			"You call out…all that you see.",
			"~",
			"On-on as you name,",
			"Continue to twist -",
			"You say what not said before.",
			"~",

			"You fold and you fiddle,",
			"You chant and you cast -",
			"You create of the world a spell.",
			"~",

			,
			"Now ingest of their names,",
			"Swallow them whole -",
			"You make them your flesh and your blood.",
			"~",

			"With their names so imbibed",
			"Spill them out once more -",
			"You speak their intent and their charm.",
			"~",

			"You tell them their names",
			"And who they will be -",
			"Their meaning be so inscribed.",
		],
	},
	{
		subtitle: "Dreamers ",
		image: "",
		content: [
			"'If only if only,'",
			"They said to the world,",
			"'If only you could be what I wanted.'",

			"'If only if only,'",
			"The world replied,",
			"'If only you knew what you wanted.'",

			"With a head full of stars,",
			"And a dream so big,",
			"That across all their minds",
			"It stood.",

			"Such that one dreamer alone",
			"Had no view of the whole,",
			"Of the dreamer in true that they dreamt.",

			"One and the same,",
			"The world and the dream,",
			"Whispering back and forth.",

			"To know is to unwant and to want is to unknow,",
			"So forevering shall we a-dreamer.",
		],
	},
	{
		subtitle: "Platonic",
		image: "",
		content: [
			"In the world of 3 and beyond,",
			"There are 3 of 3,",
			"One of 4,",
			"And",
			"One of 5.",
			"~",
			"One 3 is 4",
			"And",
			"One 3 is 8",
			"And",
			"One final 3 is 20.",
			"~",
			"That the 4 is 6",
			"And 5 is 12",
			"Is no small thing,",
			"Though not one itself is small.",
			"~",
			"For 4",
			"And",
			"8",
			"And",
			"20",
			"And",
			"6",
			"Tile the plane eternal,",
			"~",
			"While 12 of 5",
			"Tiles none at all",
			"For wrapped",
			"Is its forever!",
		],
	},
	{
		subtitle: "Memeplex",
		image: "",
		content: [
			"And there they stand laughing,",
			"Laughing, laughing, hahaha",
			"As we dance and forget.",
			"~",
			"Forget of our names",
			"For theirs",
			"And their numbers.",
			"~",
			"Their signs and their symbols,",
			"As strings and edges,",
			"Holding our bodies aloft",
			"As our beings asunder.",
		],
	},
]
